server:
  port: 8081

spring:
  application:
    name: auth
  
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey
  access-token:
    expiration: 900000  # 15 минут
  refresh-token:
    expiration: 604800000  # 7 дней

logging:
  level:
    com.reactiverates.auth: DEBUG

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    doc-expansion: none
    tagsSorter: alpha
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json