server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://config-user:config-password@localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      username: config-user
      password: config-password
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 5
  
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  grpc:
    client:
      channels:
        users-service:
          address: localhost:9090
          negotiation-type: plaintext

jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey
  access-token:
    expiration: 900000  # 15 минут
  refresh-token:
    expiration: 604800000  # 7 дней

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    com.reactiverates.auth: DEBUG

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    doc-expansion: none
    tagsSorter: alpha
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# OpenAPI custom configuration
openapi:
  server:
    dev:
      url: http://localhost:${server.port}
      description: Локальная среда разработки
    prod:
      url: https://api.reactiverates.com
      description: Продакшн сервер